apiVersion: v1
kind: Service
metadata:
  name: dumbkv-svc
  labels:
    monitor: enabled   # to help the prometheus scrape metric
spec:
  selector: {}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
