apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=        # "postgres" in base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=   # "postgres" in base64
  POSTGRES_DB: cG9zdGdyZXM=     # "postgres" in base64
