apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbkv-app
spec:
  template:
    spec:
      containers:
        - name: dumbkv-container  # container name is a must for strategic patches
          envFrom:
            - configMapRef:
                name: config
      volumes:
        - name: dumbkv-storage
          persistentVolumeClaim:
            claimName: dumbkv-pvc
