apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - namespace.yaml

namespace: ns-sqlite # suffix does not apply to namespace
nameSuffix: -sqlite
namePrefix: dev-
labels:
  - pairs:
      type: sqlite
    includeSelectors: true

patches:
  - path: deployment-patch.yaml
  - path: svc-patch.yaml
  - path: pvc-patch.yaml

