apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor
  labels:
    app: monitor
    release: prometheus
spec:
  selector:
    matchLabels:
      app: dumbkv
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s