apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
  namespace: default
spec:
  secretName: letsencrypt   # Secret where the certificate will be stored
  dnsNames:
    - www.shanana.shop
    - shanana.shop
    - postgres.shanana.shop
    - monitor.shanana.shop
  issuerRef:
    name: dumbkv-cl
    kind: ClusterIssuer
