apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: monitor-route
  namespace: monitoring
spec:
  parentRefs:
    - name: dumbkv-gateway
      namespace: default
  hostnames:
    - monitor.shanana.shop
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /prometheus
      backendRefs:
        - name: kube-prometheus-stack-prometheus
          port: 9090
