apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-applications
  namespace: monitoring
spec:
  evaluationInterval: 30s
  image: quay.io/prometheus/prometheus:v3.4.1
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  logLevel: info
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 1
  retention: 1d
  scrapeInterval: 30s
  serviceAccountName: prometheus-applications
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      monitor: enabled
  shards: 1
  version: v3.4.1