apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs
provisioner: pd.csi.storage.gke.io  # since I am using GKE
parameters:
  type: pd-ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
